/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBasePool, IBasePoolInterface } from "../IBasePool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "distributeRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBasePool__factory {
  static readonly abi = _abi;
  static createInterface(): IBasePoolInterface {
    return new utils.Interface(_abi) as IBasePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBasePool {
    return new Contract(address, _abi, signerOrProvider) as IBasePool;
  }
}
