/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITimeLockPool, ITimeLockPoolInterface } from "../ITimeLockPool";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class ITimeLockPool__factory {
  static readonly abi = _abi;
  static createInterface(): ITimeLockPoolInterface {
    return new utils.Interface(_abi) as ITimeLockPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITimeLockPool {
    return new Contract(address, _abi, signerOrProvider) as ITimeLockPool;
  }
}
