/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AbstractRewardsInterface extends utils.Interface {
  contractName: "AbstractRewards";
  functions: {
    "POINTS_MULTIPLIER()": FunctionFragment;
    "cumulativeRewardsOf(address)": FunctionFragment;
    "pointsCorrection(address)": FunctionFragment;
    "pointsPerShare()": FunctionFragment;
    "withdrawableRewardsOf(address)": FunctionFragment;
    "withdrawnRewards(address)": FunctionFragment;
    "withdrawnRewardsOf(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "POINTS_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cumulativeRewardsOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "pointsCorrection",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "pointsPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawableRewardsOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawnRewards",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawnRewardsOf",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "POINTS_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cumulativeRewardsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pointsCorrection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pointsPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawableRewardsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawnRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawnRewardsOf",
    data: BytesLike
  ): Result;

  events: {
    "RewardsDistributed(address,uint256)": EventFragment;
    "RewardsWithdrawn(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RewardsDistributed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardsWithdrawn"): EventFragment;
}

export type RewardsDistributedEvent = TypedEvent<
  [string, BigNumber],
  { by: string; rewardsDistributed: BigNumber }
>;

export type RewardsDistributedEventFilter =
  TypedEventFilter<RewardsDistributedEvent>;

export type RewardsWithdrawnEvent = TypedEvent<
  [string, BigNumber],
  { by: string; fundsWithdrawn: BigNumber }
>;

export type RewardsWithdrawnEventFilter =
  TypedEventFilter<RewardsWithdrawnEvent>;

export interface AbstractRewards extends BaseContract {
  contractName: "AbstractRewards";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AbstractRewardsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    POINTS_MULTIPLIER(overrides?: CallOverrides): Promise<[BigNumber]>;

    cumulativeRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pointsCorrection(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pointsPerShare(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawableRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawnRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawnRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  POINTS_MULTIPLIER(overrides?: CallOverrides): Promise<BigNumber>;

  cumulativeRewardsOf(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pointsCorrection(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  pointsPerShare(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawableRewardsOf(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawnRewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  withdrawnRewardsOf(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    POINTS_MULTIPLIER(overrides?: CallOverrides): Promise<BigNumber>;

    cumulativeRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pointsCorrection(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pointsPerShare(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawableRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawnRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawnRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "RewardsDistributed(address,uint256)"(
      by?: string | null,
      rewardsDistributed?: null
    ): RewardsDistributedEventFilter;
    RewardsDistributed(
      by?: string | null,
      rewardsDistributed?: null
    ): RewardsDistributedEventFilter;

    "RewardsWithdrawn(address,uint256)"(
      by?: string | null,
      fundsWithdrawn?: null
    ): RewardsWithdrawnEventFilter;
    RewardsWithdrawn(
      by?: string | null,
      fundsWithdrawn?: null
    ): RewardsWithdrawnEventFilter;
  };

  estimateGas: {
    POINTS_MULTIPLIER(overrides?: CallOverrides): Promise<BigNumber>;

    cumulativeRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pointsCorrection(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pointsPerShare(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawableRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawnRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawnRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    POINTS_MULTIPLIER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cumulativeRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pointsCorrection(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pointsPerShare(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawableRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawnRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawnRewardsOf(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
